from PyQt6 import QtCore, QtGui, QtWidgets
from .widget.image_label import ClickableImageLabel
from .widget.list_widget import KeypointListWidget

class UI_LabelaryDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        Dialog.setMinimumSize(QtCore.QSize(700, 400))
        Dialog.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.video_combo = QtWidgets.QComboBox(parent=Dialog)
        self.video_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.video_combo.setObjectName("video_combo")
        self.horizontalLayout.addWidget(self.video_combo)
        self.label_combo = QtWidgets.QComboBox(parent=Dialog)
        self.label_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_combo.setObjectName("label_combo")
        self.horizontalLayout.addWidget(self.label_combo)
        self.mode_combo = QtWidgets.QComboBox(parent=Dialog)
        self.mode_combo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mode_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.mode_combo.setObjectName("mode_combo")
        self.horizontalLayout.addWidget(self.mode_combo)

        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.load_data_button = QtWidgets.QPushButton(parent=Dialog)
        self.load_data_button.setMinimumSize(QtCore.QSize(200, 0))
        self.load_data_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.load_data_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.load_data_button.setObjectName("load_data_button")
        self.gridLayout.addWidget(self.load_data_button, 0, 1, 1, 1)

        self.auto_label_layout = QtWidgets.QHBoxLayout()
        self.auto_label_layout.setObjectName("auto_label_layout")
        self.automatic_label_checkbox = QtWidgets.QCheckBox(parent=Dialog)
        self.automatic_label_checkbox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.automatic_label_checkbox.setObjectName("automatic_label_checkbox")
        self.auto_label_layout.addWidget(self.automatic_label_checkbox)
        self.model_path_edit = QtWidgets.QLabel(parent=Dialog)
        self.model_path_edit.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.model_path_edit.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.model_path_edit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.model_path_edit.setWordWrap(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        self.model_path_edit.setSizePolicy(sizePolicy)
        self.model_path_edit.setMinimumWidth(0)
        self.model_path_edit.setObjectName("model_path_edit")
        self.auto_label_layout.addWidget(self.model_path_edit, 1)
        self.load_model_button = QtWidgets.QPushButton(parent=Dialog)
        self.load_model_button.setMinimumSize(QtCore.QSize(200, 0))
        self.load_model_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.load_model_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.load_model_button.setObjectName("load_model_button")
        self.auto_label_layout.addWidget(self.load_model_button)
        self.gridLayout.addLayout(self.auto_label_layout, 1, 0, 1, 2)

        self.mini_training_layout = QtWidgets.QHBoxLayout()
        self.mini_training_layout.setObjectName("mini_training_layout")
        self.mini_training_label = QtWidgets.QLabel(parent=Dialog)
        self.mini_training_label.setObjectName("mini_training_label")
        self.mini_training_layout.addWidget(self.mini_training_label)
        self.auto_label_confidence_label = QtWidgets.QLabel(parent=Dialog)
        self.auto_label_confidence_label.setObjectName("auto_label_confidence_label")
        self.mini_training_layout.addWidget(self.auto_label_confidence_label)
        self.auto_label_confidence_spin = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.auto_label_confidence_spin.setDecimals(2)
        self.auto_label_confidence_spin.setMinimum(0.01)
        self.auto_label_confidence_spin.setMaximum(1.0)
        self.auto_label_confidence_spin.setSingleStep(0.05)
        self.auto_label_confidence_spin.setProperty("value", 0.10)
        self.auto_label_confidence_spin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.auto_label_confidence_spin.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.auto_label_confidence_spin.setObjectName("auto_label_confidence_spin")
        self.mini_training_layout.addWidget(self.auto_label_confidence_spin)
        self.mini_training_layout.addSpacing(16)
        self.training_section_label = QtWidgets.QLabel(parent=Dialog)
        self.training_section_label.setObjectName("training_section_label")
        self.mini_training_layout.addWidget(self.training_section_label)
        self.mini_training_epochs_label = QtWidgets.QLabel(parent=Dialog)
        self.mini_training_epochs_label.setObjectName("mini_training_epochs_label")
        self.mini_training_layout.addWidget(self.mini_training_epochs_label)
        self.mini_training_epochs_spin = QtWidgets.QSpinBox(parent=Dialog)
        self.mini_training_epochs_spin.setMinimum(1)
        self.mini_training_epochs_spin.setMaximum(1000)
        self.mini_training_epochs_spin.setProperty("value", 10)
        self.mini_training_epochs_spin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.mini_training_epochs_spin.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.mini_training_epochs_spin.setObjectName("mini_training_epochs_spin")
        self.mini_training_layout.addWidget(self.mini_training_epochs_spin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mini_training_layout.addItem(spacerItem1)
        self.mini_training_button = QtWidgets.QPushButton(parent=Dialog)
        self.mini_training_button.setMinimumSize(QtCore.QSize(200, 0))
        self.mini_training_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mini_training_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.mini_training_button.setObjectName("mini_training_button")
        self.mini_training_layout.addWidget(self.mini_training_button)
        self.gridLayout.addLayout(self.mini_training_layout, 2, 0, 1, 2)

        self.skeleton_video_viewer = ClickableImageLabel(parent=Dialog)
        self.skeleton_video_viewer.setAutoFillBackground(True)
        self.skeleton_video_viewer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.skeleton_video_viewer.setText("")
        self.skeleton_video_viewer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.skeleton_video_viewer.setObjectName("skeleton_video_viewer")
        self.gridLayout.addWidget(self.skeleton_video_viewer, 3, 0, 4, 1)
        self.kpt_list_title = QtWidgets.QLabel(parent=Dialog)
        self.kpt_list_title.setMaximumSize(QtCore.QSize(200, 16777215))
        self.kpt_list_title.setObjectName("kpt_list_title")
        self.gridLayout.addWidget(self.kpt_list_title, 3, 1, 1, 1)
        self.kpt_list = KeypointListWidget(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpt_list.sizePolicy().hasHeightForWidth())
        self.kpt_list.setSizePolicy(sizePolicy)
        self.kpt_list.setMinimumSize(QtCore.QSize(0, 0))
        self.kpt_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.kpt_list.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.kpt_list.setObjectName("kpt_list")
        self.gridLayout.addWidget(self.kpt_list, 4, 1, 1, 1)

        self.color_combo = QtWidgets.QComboBox(parent=Dialog)
        self.color_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.color_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.color_combo.setObjectName("color_combo")
        self.gridLayout.addWidget(self.color_combo, 5, 1, 1, 1)
        self.frame_slider = QtWidgets.QSlider(parent=Dialog)
        self.frame_slider.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.frame_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout.addWidget(self.frame_slider, 7, 0, 2, 1)
        self.frame_number_label = QtWidgets.QLabel(parent=Dialog)
        self.frame_number_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_number_label.setObjectName("frame_number_label")
        self.gridLayout.addWidget(self.frame_number_label, 7, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(parent=Dialog)
        self.save_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.save_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 8, 1, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play_button = QtWidgets.QPushButton(parent=Dialog)
        self.play_button.setMinimumSize(QtCore.QSize(100, 0))
        self.play_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.play_button.setObjectName("play_button")
        self.speed_spin = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.speed_spin.setRange(0.1, 4.0)
        self.speed_spin.setSingleStep(0.1)
        self.speed_spin.setDecimals(1)
        self.speed_spin.setValue(1.0)
        self.speed_spin.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.speed_spin.setMaximumWidth(80)
        self.speed_spin.setObjectName("speed_spin")
        self.frame_jump_spin = QtWidgets.QSpinBox(parent=Dialog)
        self.frame_jump_spin.setMinimum(0)
        self.frame_jump_spin.setMaximum(0)
        self.frame_jump_spin.setValue(0)
        self.frame_jump_spin.setKeyboardTracking(False)
        self.frame_jump_spin.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.frame_jump_spin.setMaximumWidth(120)
        self.frame_jump_spin.setObjectName("frame_jump_spin")
        self.horizontalLayout_2.addWidget(self.play_button)
        self.horizontalLayout_2.addWidget(self.speed_spin)
        self.horizontalLayout_2.addWidget(self.frame_jump_spin)
        spacerItem = QtWidgets.QSpacerItem(427, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Labelary"))
        self.load_data_button.setText(_translate("Dialog", "Load Data"))
        self.automatic_label_checkbox.setText(_translate("Dialog", "Automatic Labeling"))
        self.model_path_edit.setText(_translate("Dialog", ""))
        self.load_model_button.setText(_translate("Dialog", "Browse/Load Model"))
        self.mini_training_label.setText(_translate("Dialog", "<b>Inference</b>"))
        self.auto_label_confidence_label.setText(_translate("Dialog", "Confidence"))
        self.training_section_label.setText(_translate("Dialog", "<b>Training</b>"))
        self.mini_training_epochs_label.setText(_translate("Dialog", "Epochs"))
        self.mini_training_button.setText(_translate("Dialog", "Run Mini Training"))
        self.kpt_list_title.setText(_translate("Dialog", "Keypoint List"))
        self.frame_number_label.setText(_translate("Dialog", "0 /  total"))
        self.save_button.setText(_translate("Dialog", "Save/Export"))
        self.play_button.setText(_translate("Dialog", "play"))
        self.speed_spin.setSuffix(_translate("Dialog", "×"))
        self.frame_jump_spin.setPrefix(_translate("Dialog", "Frame "))
