from PyQt6 import QtCore, QtGui, QtWidgets
from .widget.image_label import ClickableImageLabel
from .widget.list_widget import KeypointListWidget

class UI_LabelaryDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        Dialog.setMinimumSize(QtCore.QSize(700, 400))
        Dialog.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.video_combo = QtWidgets.QComboBox(parent=Dialog)
        self.video_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.video_combo.setObjectName("video_combo")
        self.horizontalLayout.addWidget(self.video_combo)
        self.label_combo = QtWidgets.QComboBox(parent=Dialog)
        self.label_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_combo.setObjectName("label_combo")
        self.horizontalLayout.addWidget(self.label_combo)
        self.mode_combo = QtWidgets.QComboBox(parent=Dialog)
        self.mode_combo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mode_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.mode_combo.setObjectName("mode_combo")
        self.horizontalLayout.addWidget(self.mode_combo)

        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.load_data_button = QtWidgets.QPushButton(parent=Dialog)
        self.load_data_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.load_data_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.load_data_button.setObjectName("load_data_button")
        self.gridLayout.addWidget(self.load_data_button, 0, 1, 1, 1)

        self.skeleton_video_viewer = ClickableImageLabel(parent=Dialog)
        self.skeleton_video_viewer.setAutoFillBackground(True)
        self.skeleton_video_viewer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.skeleton_video_viewer.setText("")
        self.skeleton_video_viewer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.skeleton_video_viewer.setObjectName("skeleton_video_viewer")
        self.gridLayout.addWidget(self.skeleton_video_viewer, 1, 0, 4, 1)
        self.kpt_list_title = QtWidgets.QLabel(parent=Dialog)
        self.kpt_list_title.setMaximumSize(QtCore.QSize(200, 16777215))
        self.kpt_list_title.setObjectName("kpt_list_title")
        self.gridLayout.addWidget(self.kpt_list_title, 1, 1, 1, 1)
        self.kpt_list = KeypointListWidget(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpt_list.sizePolicy().hasHeightForWidth())
        self.kpt_list.setSizePolicy(sizePolicy)
        self.kpt_list.setMinimumSize(QtCore.QSize(0, 0))
        self.kpt_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.kpt_list.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.kpt_list.setObjectName("kpt_list")
        self.gridLayout.addWidget(self.kpt_list, 2, 1, 1, 1)

        self.color_combo = QtWidgets.QComboBox(parent=Dialog)
        self.color_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.color_combo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.color_combo.setObjectName("color_combo")
        self.gridLayout.addWidget(self.color_combo, 3, 1, 1, 1)
        self.frame_slider = QtWidgets.QSlider(parent=Dialog)
        self.frame_slider.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.frame_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout.addWidget(self.frame_slider, 5, 0, 2, 1)
        self.frame_number_label = QtWidgets.QLabel(parent=Dialog)
        self.frame_number_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_number_label.setObjectName("frame_number_label")
        self.gridLayout.addWidget(self.frame_number_label, 5, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(parent=Dialog)
        self.save_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.save_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 6, 1, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play_button = QtWidgets.QPushButton(parent=Dialog)
        self.play_button.setMinimumSize(QtCore.QSize(100, 0))
        self.play_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.play_button.setObjectName("play_button")
        self.speed_spin = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.speed_spin.setRange(0.1, 4.0)
        self.speed_spin.setSingleStep(0.1)
        self.speed_spin.setDecimals(1)
        self.speed_spin.setValue(1.0)
        self.speed_spin.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.speed_spin.setMaximumWidth(80)
        self.speed_spin.setObjectName("speed_spin")
        self.horizontalLayout_2.addWidget(self.play_button)
        self.horizontalLayout_2.addWidget(self.speed_spin)
        spacerItem = QtWidgets.QSpacerItem(427, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Labelary"))
        self.load_data_button.setText(_translate("Dialog", "Load Data"))
        self.kpt_list_title.setText(_translate("Dialog", "Keypoint List"))
        self.frame_number_label.setText(_translate("Dialog", "0 /  total"))
        self.save_button.setText(_translate("Dialog", "Save/Export"))
        self.play_button.setText(_translate("Dialog", "play"))